version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.1

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            frontend/.* frontend-changed true
            backend/.* backend-changed true
          base-revision: origin/main
