version: 2.1

parameters:
  frontend-changed:
    type: boolean
    default: false
  backend-changed:
    type: boolean
    default: false

jobs:
  echo-parameters:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "frontend-changed ... << pipeline.parameters.frontend-changed >>"
      - run: echo "backend-changed ... << pipeline.parameters.backend-changed >>"
      - run: echo "pipeline.git.branch ... << pipeline.git.branch >>"
      - run: echo "pipeline.git.tag ... << pipeline.git.tag >>"
  frontend-job:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition: << pipeline.parameters.frontend-changed >>
          steps:
            run: echo "frontend-job is executed"
      - unless:
          condition: << pipeline.parameters.frontend-changed >>
          steps:
            run: echo "Skip frontend-job"
  backend-job:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition: << pipeline.parameters.backend-changed >>
          steps:
            run: echo "backend-job is executed"
      - unless:
          condition: << pipeline.parameters.backend-changed >>
          steps:
            run: echo "Skip backend-job"
  develop-branch-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "develop-branch-job is executed"
  main-branch-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "main-branch-job is executed"
  tag-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "tag-job is executed"
  tag-only-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "tag-only-job is executed"
  main-branch-tag-only-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "main-branch-tag-only-job is executed"

workflows:
  run_all_jobs:
    jobs:
      - echo-parameters:
          filters:
            tags:
              only: /.*/
      - frontend-job:
          requires:
            - echo-parameters
          filters:
            tags:
              only: /.*/
      - backend-job:
          requires:
            - echo-parameters
          filters:
            tags:
              only: /.*/
      - main-branch-job:
          requires:
            - frontend-job
            - backend-job
          filters:
            branches:
              only: main
            tags:
              only: /.*/
      - develop-branch-job:
          requires:
            - frontend-job
            - backend-job
          filters:
            branches:
              only: develop
            tags:
              only: /.*/
      - tag-job:
          requires:
            - main-branch-job
            - develop-branch-job
          filters:
            tags:
              only: /.*/
      - tag-only-job:
          requires:
            - main-branch-job
            - develop-branch-job
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - main-branch-tag-only-job:
          requires:
            - tag-job
            - tag-only-job
          filters:
            branches:
              only: main
            tags:
              only: /.*/
