version: 2.1

parameters:
  frontend-changed:
    type: boolean
    default: false
  backend-changed:
    type: boolean
    default: false

jobs:
  frontend-job:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition: << pipeline.parameters.frontend-changed >>
          steps:
            run: echo "frontend-job is executed"
      - unless:
          condition: << pipeline.parameters.frontend-changed >>
          steps:
            run: echo "Skip frontend-job"
  backend-job:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition: << pipeline.parameters.backend-changed >>
          steps:
            run: echo "backend-job is executed"
      - unless:
          condition: << pipeline.parameters.backend-changed >>
          steps:
            run: echo "Skip backend-job"
  develop-branch-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "develop-branch-job is executed"
  main-branch-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "main-branch-job is executed"

workflows:
  run_all_jobs:
    jobs:
      - frontend-job
      - backend-job
      - develop-branch-job:
          requires:
            - frontend-job
            - backend-job
          filters:
            branches:
              only: develop
      - main-branch-job:
          requires:
            - frontend-job
            - backend-job
          filters:
            branches:
              only: main
